WITH FREE_TRIAL AS (
    SELECT USER_ID, AVG(ACTIVITY_DURATION) AS AVG_TIME
    FROM USERACTIVITY
    WHERE ACTIVITY_TYPE = 'free_trial'
    GROUP BY USER_ID
),

PAID AS (
    SELECT USER_ID, AVG(ACTIVITY_DURATION) AS AVG_TIME
    FROM USERACTIVITY
    WHERE ACTIVITY_TYPE = 'paid'
    GROUP BY USER_ID
)

SELECT P.USER_ID, ROUND(F.AVG_TIME,2) AS TRIAL_AVG_DURATION, ROUND(P.AVG_TIME,2) AS PAID_AVG_DURATION
FROM FREE_TRIAL F RIGHT JOIN PAID P 
ON F.USER_ID = P.USER_ID
ORDER BY P.USER_ID