WITH DAY AS (
    SELECT VISITED_ON, SUM(AMOUNT) AS AMOUNT
    FROM CUSTOMER
    GROUP BY VISITED_ON
)

SELECT A.VISITED_ON, SUM(B.AMOUNT) AS AMOUNT, ROUND(AVG(B.AMOUNT),2) AS AVERAGE_AMOUNT
FROM DAY A JOIN DAY B
ON B.VISITED_ON BETWEEN DATE_SUB(A.VISITED_ON, INTERVAL 6 DAY) AND A.VISITED_ON
GROUP BY A.VISITED_ON
HAVING COUNT(B.VISITED_ON) = 7
ORDER BY A.VISITED_ON