WITH CAR_INFO AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, D.DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON C.CAR_TYPE = D.CAR_TYPE
    WHERE
        D.DURATION_TYPE = '30일 이상' 
    AND C.CAR_TYPE IN ('세단','SUV'))

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (1 - (DISCOUNT_RATE/100)) * 30, 0) AS FEE
FROM CAR_INFO
WHERE DAILY_FEE * (1 - (DISCOUNT_RATE/100)) * 30 >= 500000 AND
      DAILY_FEE * (1 - (DISCOUNT_RATE/100)) * 30 < 2000000 AND
      CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE NOT (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01'))
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;