WITH CTE AS (SELECT A.TEST_ID, A.PATIENT_ID, MIN(A.TEST_DATE) AS P_DATE, MIN(B.TEST_DATE) AS C_DATE
             FROM COVID_TESTS A JOIN COVID_TESTS B
             ON A.PATIENT_ID = B.PATIENT_ID 
             AND A.RESULT = "Positive" AND B.RESULT = "Negative"
             AND B.TEST_DATE >= A.TEST_DATE
             GROUP BY A.PATIENT_ID)

SELECT C.PATIENT_ID, PATIENT_NAME, AGE, DATEDIFF(C_DATE, P_DATE) AS RECOVERY_TIME
FROM CTE C JOIN PATIENTS P
ON C.PATIENT_ID = P.PATIENT_ID
ORDER BY RECOVERY_TIME, PATIENT_NAME