WITH RECURSIVE BUS AS (
    SELECT TURN, PERSON_NAME, WEIGHT, WEIGHT AS TOTAL_WEIGHT
    FROM QUEUE
    WHERE TURN = 1

    UNION ALL

    SELECT Q.TURN, Q.PERSON_NAME, Q.WEIGHT, Q.WEIGHT + B.TOTAL_WEIGHT
    FROM QUEUE Q JOIN BUS B
    ON Q.TURN = B.TURN + 1
    WHERE B.TOTAL_WEIGHT + Q.WEIGHT <= 1000
)

SELECT PERSON_NAME
FROM BUS
ORDER BY TURN DESC
LIMIT 1