WITH CTE AS (
    SELECT *, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RNK
    FROM EMPLOYEE
)

SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, SALARY
FROM CTE E JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE RNK <= 3