SELECT P.PRODUCT_ID, IFNULL(ROUND((SUM(PRICE * UNITS) / SUM(UNITS)),2),0) AS AVERAGE_PRICE
FROM PRICES P LEFT JOIN UNITSSOLD U
ON START_DATE <= PURCHASE_DATE AND END_DATE >= PURCHASE_DATE AND P.PRODUCT_ID = U.PRODUCT_ID
GROUP BY 1