SELECT BOOK_ID, TITLE, AUTHOR, GENRE, PUBLICATION_YEAR, TOTAL_COPIES AS CURRENT_BORROWERS
FROM LIBRARY_BOOKS
WHERE (BOOK_ID, TOTAL_COPIES) IN (SELECT BOOK_ID, COUNT(BOOK_ID)
                                  FROM BORROWING_RECORDS
                                  WHERE RETURN_DATE IS NULL
                                  GROUP BY BOOK_ID)
ORDER BY TOTAL_COPIES DESC, TITLE