SELECT STOCK_NAME, SUM(CASE WHEN OPERATION = 'Sell' THEN PRICE ELSE 0 END)
                    - SUM(CASE WHEN OPERATION = 'Buy' THEN PRICE ELSE 0 END) AS CAPITAL_GAIN_LOSS
FROM STOCKS
GROUP BY STOCK_NAME