WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GENERATION, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, C.GENERATION + 1 AS GENERATION, E.PARENT_ID AS PARENT_ID
    FROM ECOLI_DATA E JOIN CTE C
    ON E.PARENT_ID = C.ID
)

SELECT COUNT(*) AS COUNT, P.GENERATION
FROM CTE P
WHERE NOT EXISTS (SELECT 1
                  FROM CTE C
                  WHERE C.PARENT_ID = P.ID)
GROUP BY P.GENERATION
ORDER BY P.GENERATION