SELECT QUERY_NAME, ROUND(SUM(RATING/POSITION) / COUNT(1),2) AS QUALITY, 
    ROUND(SUM(CASE WHEN RATING < 3 THEN 1
                ELSE 0 END) / COUNT(1) * 100,2) AS POOR_QUERY_PERCENTAGE 
FROM QUERIES
GROUP BY 1