WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME 
    WHERE HOUR < 23)
    
SELECT T.HOUR, COUNT(DATETIME) AS COUNT
FROM TIME T LEFT JOIN ANIMAL_OUTS A
ON T.HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR