SELECT A.EMPLOYEE_ID, A.NAME, COUNT(1) AS REPORTS_COUNT, ROUND(AVG(B.AGE),0) AS AVERAGE_AGE
FROM EMPLOYEES A JOIN EMPLOYEES B
ON A.EMPLOYEE_ID = B.REPORTS_TO
GROUP BY A.EMPLOYEE_ID
ORDER BY A.EMPLOYEE_ID