SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALE
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U 
ON B.WRITER_ID = U.USER_ID
WHERE BOARD_ID IN (SELECT BOARD_ID FROM USED_GOODS_BOARD
      WHERE STATUS = "DONE")
GROUP BY USER_ID
HAVING TOTAL_SALE >= 700000
ORDER BY 3