WITH SALARY AS (
    SELECT 'High Salary' AS CATEGORY
    UNION ALL
    SELECT 'Average Salary'
    UNION ALL
    SELECT 'Low Salary'
),
ACCOUNTS_SORTED AS (
    SELECT CASE
        WHEN INCOME > 50000 THEN 'High Salary'
        WHEN INCOME >= 20000 THEN 'Average Salary'
        ELSE 'Low Salary' END AS CATEGORY
    FROM ACCOUNTS
)

SELECT S.CATEGORY, COUNT(A.CATEGORY) AS ACCOUNTS_COUNT
FROM SALARY S LEFT JOIN ACCOUNTS_SORTED A
ON S.CATEGORY = A.CATEGORY
GROUP BY S.CATEGORY