SELECT *, 
    IF(DNA_SEQUENCE LIKE 'ATG%', 1, 0) AS HAS_START,
    IF(DNA_SEQUENCE LIKE '%TAA' OR DNA_SEQUENCE LIKE '%TAG' OR DNA_SEQUENCE LIKE '%TGA', 1, 0) AS HAS_STOP,
    IF(DNA_SEQUENCE LIKE '%ATAT%', 1, 0) AS HAS_ATAT,
    IF(DNA_SEQUENCE LIKE '%GGG%', 1, 0) AS HAS_GGG
FROM SAMPLES