SELECT NAME AS RESULTS
FROM (SELECT NAME
    FROM USERS NATURAL JOIN MOVIERATING
    GROUP BY USER_ID
    ORDER BY COUNT(USER_ID) DESC, NAME
    LIMIT 1
) A

UNION ALL

SELECT TITLE AS RESULTS
FROM (SELECT TITLE
    FROM MOVIES NATURAL JOIN MOVIERATING
    WHERE YEAR(CREATED_AT) = 2020 AND MONTH(CREATED_AT) = 2
    GROUP BY MOVIE_ID
    ORDER BY AVG(RATING) DESC, TITLE
    LIMIT 1
) AS B
