SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, MAX_COL - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A INNER JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS BYEAR, 
                              MAX(SIZE_OF_COLONY) AS MAX_COL
                    FROM ECOLI_DATA
                   GROUP BY 1) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.BYEAR
ORDER BY 1, 2