SELECT A.ID, A.VISIT_DATE, A.PEOPLE
FROM STADIUM A JOIN STADIUM B JOIN STADIUM C
ON A.ID = B.ID + 1 AND B.ID = C.ID + 1
WHERE A.PEOPLE >= 100 AND B.PEOPLE >= 100 AND C.PEOPLE >= 100

UNION

SELECT B.ID, B.VISIT_DATE, B.PEOPLE
FROM STADIUM A JOIN STADIUM B JOIN STADIUM C
ON A.ID = B.ID + 1 AND B.ID = C.ID + 1
WHERE A.PEOPLE >= 100 AND B.PEOPLE >= 100 AND C.PEOPLE >= 100

UNION

SELECT C.ID, C.VISIT_DATE, C.PEOPLE
FROM STADIUM A JOIN STADIUM B JOIN STADIUM C
ON A.ID = B.ID + 1 AND B.ID = C.ID + 1
WHERE A.PEOPLE >= 100 AND B.PEOPLE >= 100 AND C.PEOPLE >= 100

ORDER BY ID