WITH FIRST AS (
    SELECT STUDENT_ID, SUBJECT, SCORE, EXAM_DATE
    FROM SCORES
    WHERE (STUDENT_ID, SUBJECT, EXAM_DATE) IN (SELECT STUDENT_ID, SUBJECT, MIN(EXAM_DATE)
                                             FROM SCORES
                                             GROUP BY STUDENT_ID, SUBJECT)
),
LAST AS (
    SELECT STUDENT_ID, SUBJECT, SCORE, EXAM_DATE
    FROM SCORES
    WHERE (STUDENT_ID, SUBJECT, EXAM_DATE) IN (SELECT STUDENT_ID, SUBJECT, MAX(EXAM_DATE)
                                             FROM SCORES
                                             GROUP BY STUDENT_ID, SUBJECT)
)

SELECT F.STUDENT_ID, F.SUBJECT, F.SCORE AS FIRST_SCORE, L.SCORE AS LATEST_SCORE
FROM FIRST F JOIN LAST L
ON F.STUDENT_ID = L.STUDENT_ID AND F.SUBJECT = L.SUBJECT
WHERE F.SCORE < L.SCORE
ORDER BY F.STUDENT_ID, F.SUBJECT